services:
  - type: web
    name: adder-mcp
    env: python          # native runtime
    plan: free           # or “starter”, “standard”, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    autoDeploy: true
